using AutoMapper;
using Notes.MvcApp.Models;
using Notes.MvcApp.Services.Notes.API.Services.Autogenerated;

namespace Notes.MvcApp.Services.Automapper
{
    public  class ServicelayerProfile : Profile
    {
        public ServicelayerProfile()
        {
            CreateMap<NoteApiModel, NoteViewModel>().ReverseMap();
        }
    }
}
