using Notes.MvcApp.Services.Notes.API.Services.Autogenerated;

namespace Notes.MvcApp.Notes.Api.Configuration
{
    public static class NotesApiServiceCollectionExtensions
    {
        public static IServiceCollection AddNotesApi(this IServiceCollection services)
        {
            var notesApiConfiguration = new NotesApiConfiguration();

            services.BuildServiceProvider().GetService<IConfiguration>()?.GetSection(nameof(NotesApiConfiguration)).Bind(notesApiConfiguration);

            services.AddHttpClient<NotesApiConnector>(client =>
            {
                client.BaseAddress = new Uri(notesApiConfiguration.BaseUrl ?? throw new ApplicationException($"valid base url not supplied for {nameof(notesApiConfiguration)}"));
                client.DefaultRequestHeaders.Add("Accept", "application/json");
            }).AddUserAccessTokenHandler();
            return services;
        }
    }
}
