FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src 

# Copy and restore IdentityService project
COPY *.csproj ./ 
RUN dotnet restore 

# Copy the remaining code
COPY . ./

RUN dotnet publish -c Release -o /app 

# Phase #2, Build final image 

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS release

WORKDIR /app

COPY --from=build /app .


EXPOSE 80 443

ENV ASPNETCORE_URLS=http://+:80;https://+:443

ENTRYPOINT ["dotnet", "MakeBitByte.IDP.dll"]