// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.API.Datalayer.Context;

#nullable disable

namespace Notes.Api.Datalayer.Migrations
{
    [DbContext(typeof(DatalayerContext))]
    partial class DatalayerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Notes.API.Datalayer.DbSet.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("891952fb-df7c-4493-95ca-f8d4628ecc85"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet porttitor eget dolor morbi non. Varius vel pharetra vel turpis nunc eget. Augue ut lectus arcu bibendum at varius. Accumsan tortor posuere ac ut. In tellus integer feugiat scelerisque varius morbi enim nunc. Turpis massa sed elementum tempus egestas sed sed risus. Volutpat consequat mauris nunc congue. Mauris commodo quis imperdiet massa tincidunt nunc. Mattis rhoncus urna neque viverra. Arcu odio ut sem nulla pharetra diam sit amet. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Etiam tempor orci eu lobortis elementum nibh tellus. Cursus vitae congue mauris rhoncus aenean.",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Lorem ipsum",
                            Title = "(A note by Arjun) consectetur adipiscing elit",
                            UserId = new Guid("1c94f897-2af3-46d4-a131-8a147d18a2f2")
                        },
                        new
                        {
                            Id = new Guid("77eede84-249e-49bd-963e-34ce882bb0ce"),
                            Content = "Nunc lobortis mattis aliquam faucibus purus in massa tempor. Ultricies leo integer malesuada nunc. Eget duis at tellus at urna. Aenean vel elit scelerisque mauris pellentesque pulvinar. Quisque id diam vel quam elementum pulvinar etiam non quam. Lectus urna duis convallis convallis tellus id interdum velit.  ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Nunc lobortis mattis aliquam faucibus purus in ",
                            Title = "(A note by Arjun) Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan.",
                            UserId = new Guid("1c94f897-2af3-46d4-a131-8a147d18a2f2")
                        },
                        new
                        {
                            Id = new Guid("5ad62e22-590e-4586-b46c-47d64562f5e4"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet porttitor eget dolor morbi non. Varius vel pharetra vel turpis nunc eget. Augue ut lectus arcu bibendum at varius. Accumsan tortor posuere ac ut. In tellus integer feugiat scelerisque varius morbi enim nunc. Turpis massa sed elementum tempus egestas sed sed risus. Volutpat consequat mauris nunc congue. Mauris commodo quis imperdiet massa tincidunt nunc. Mattis rhoncus urna neque viverra. Arcu odio ut sem nulla pharetra diam sit amet. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Etiam tempor orci eu lobortis elementum nibh tellus. Cursus vitae congue mauris rhoncus aenean.",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
                            Title = "(A note by Arjun) consectetur adipiscing elit",
                            UserId = new Guid("1c94f897-2af3-46d4-a131-8a147d18a2f2")
                        },
                        new
                        {
                            Id = new Guid("72dd664a-a6c0-4bd4-874c-892b86b91859"),
                            Content = "Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Pellentesque habitant morbi tristique senectus et netus et. Quam viverra orci sagittis eu volutpat odio facilisis. Facilisi cras fermentum odio eu.  ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Amet risus nullam eget felis eget nunc lobortis mattis ",
                            Title = "(A note by Arjun) Amet risus nullam eget felis eget nunc lobortis mattis ",
                            UserId = new Guid("1c94f897-2af3-46d4-a131-8a147d18a2f2")
                        },
                        new
                        {
                            Id = new Guid("4411613e-5e53-49f0-a198-74603ffdb524"),
                            Content = "In est ante in nibh mauris cursus. Massa tempor nec feugiat nisl pretium fusce id. Morbi quis commodo odio aenean sed adipiscing. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Placerat in egestas erat imperdiet.",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "In est ante in nibh mauris cursus. Massa tempor nec feugiat nisl pretium fusce id. ",
                            Title = "(A note by Arjun) In est ante in nibh mauris cursus",
                            UserId = new Guid("1c94f897-2af3-46d4-a131-8a147d18a2f2")
                        },
                        new
                        {
                            Id = new Guid("1817e743-574c-41de-9912-622685d77c52"),
                            Content = "Senectus et netus et malesuada fames ac turpis. Faucibus turpis in eu mi bibendum neque. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Vitae congue mauris rhoncus aenean vel elit scelerisque. ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Senectus et netus et malesuada fames ac turpis. ",
                            Title = "(A note by Vinita) Senectus et netus et malesuada fames ac turpis",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        },
                        new
                        {
                            Id = new Guid("b07e32d8-caa5-419b-9c0c-e246a805193f"),
                            Content = "Faucibus a pellentesque sit amet. Adipiscing elit pellentesque habitant morbi tristique. Cras semper auctor neque vitae tempus. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Faucibus a pellentesque sit amet. Adipiscing elit ",
                            Title = "(A note by Vinita) Faucibus a pellentesque sit amet. Adipiscing elit ",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        },
                        new
                        {
                            Id = new Guid("c20db987-b190-4179-b365-060953a4d0dd"),
                            Content = "Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. In egestas erat imperdiet sed euismod nisi porta. Eros donec ac odio tempor orci dapibus ultrices. Amet nisl suscipit adipiscing bibendum est. Neque convallis a cras semper auctor neque. Ut venenatis tellus in metus vulputate eu scelerisque. ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. ",
                            Title = "(A note by Vinita) Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        },
                        new
                        {
                            Id = new Guid("54b1dbf7-596d-4d03-86fa-4097dbc9f8e5"),
                            Content = "Eu mi bibendum neque egestas congue quisque egestas. At quis risus sed vulputate odio. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. A diam maecenas sed enim.` ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Eu mi bibendum neque egestas congue quisque egestas. ",
                            Title = "(A note by Vinita) Eu mi bibendum neque egestas congue quisque egestas.",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        },
                        new
                        {
                            Id = new Guid("41b3ae06-4e47-44d0-bb5d-ee5d0ad4f6c5"),
                            Content = "Id interdum velit laoreet id donec ultrices tincidunt arcu. Consequat nisl vel pretium lectus quam id. Tellus mauris a diam maecenas sed enim ut sem. Ullamcorper malesuada proin libero nunc consequat interdum. Nibh sit amet commodo nulla facilisi nullam. Tristique nulla aliquet enim tortor at auctor.",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Id interdum velit laoreet id donec ultrices tincidunt arcu. ",
                            Title = "(A note by Vinita) Id interdum velit laoreet id donec ultrices tincidunt arcu. ",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        },
                        new
                        {
                            Id = new Guid("1115c7d1-d7bd-432c-a469-c6030a5c141c"),
                            Content = "Ultrices sagittis orci a scelerisque purus semper. Maecenas sed enim ut sem viverra aliquet eget sit amet. Dui sapien eget mi proin sed libero. Donec et odio pellentesque diam volutpat commodo. Ultrices gravida dictum fusce ut. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Tristique sollicitudin nibh sit amet. ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = "Ultrices sagittis orci a scelerisque purus semper. ",
                            Title = "(A note by Vinita) Ultrices sagittis orci a scelerisque purus semper.",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        },
                        new
                        {
                            Id = new Guid("b67d9bed-fede-4c41-8ba8-9eca258a20d3"),
                            Content = " Senectus et netus et malesuada fames ac turpis. Faucibus turpis in eu mi bibendum neque. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Vitae congue mauris rhoncus aenean vel elit scelerisque. ",
                            DateCreated = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteFlag = false,
                            Description = " Senectus et netus et malesuada fames ac turpis. ",
                            Title = "(A note by Vinita) Senectus et netus et malesuada fames ac turpis",
                            UserId = new Guid("36c434ff-888f-4820-a316-1a025f8a4f0c")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
