using Notes.MvcApp.Models;
using Notes.MvcApp.Services.Notes.API.Services.Autogenerated;

namespace Notes.MvcApp.Interfaces
{
    public interface INotesService
    {
        Task<IEnumerable<NoteViewModel>> GetNotesAsync();
        Task<NoteViewModel> GetNoteAsync(Guid id);
        Task AddNoteAsync(NoteViewModel note);
        Task UpdateNoteAsync(NoteViewModel note);
        Task DeleteNoteAsync(Guid id);
        Task<IEnumerable<NoteViewModel>> SearchAsync(string searchText);
    }
}
